GET http://localhost:3001/api/v1/dev


####
POST http://localhost:3001/api/v1/dev
Content-Type: application/json

{
    "Nome": "Ricardo",
    "Avatar": "aaa",
    "Carreira": "Frontend",
    "Github": "ricardobohadana",
    "Linkedin": "ricardobohadana"
}

####
PUT http://localhost:3001/api/v1/dev
Content-Type: application/json

{
    "id": "cl0ri5gwo000074uv63aqkxn4",
    "Nome": "Andre Kaz",
    "Avatar": "",
    "Carreira": "Backend Developer",
    "Github": "andrekaz",
    "Linkedin": "andrekaz"
}